@startuml

title __COM's Class Diagram__\n

  namespace communityuni.com {
    class communityuni.com.Simulator {
        {static} + framePerSecond : double
        {static} + running : boolean
        ~ addBus : JButton
        ~ addCar : JButton
        ~ addLight : JButton
        ~ addMotorbike : JButton
        ~ addRoad : JButton
        ~ cars : ArrayList<Vehicle>
        ~ changeSpeed : JButton
        ~ down : JRadioButton
        ~ frame : JFrame
        ~ i : int
        ~ indexAttachedRoad : JTextField
        ~ info : JLabel
        ~ labelLength : JLabel
        ~ labelSpeed : JLabel
        ~ labelXPosField : JLabel
        ~ labelYPosField : JLabel
        ~ left : JRadioButton
        ~ length : JTextField
        ~ lightInfo : JLabel
        ~ lights : ArrayList<TrafficLight>
        ~ north : Container
        ~ removeLight : JButton
        ~ removeRoad : JButton
        ~ right : JRadioButton
        ~ roadInfo : JLabel
        ~ roads : ArrayList<Road>
        ~ selections : ButtonGroup
        ~ south : Container
        ~ speed : JTextField
        ~ startSim : JButton
        ~ up : JRadioButton
        ~ vehicleInfo : JLabel
        ~ west : Container
        ~ x : int
        ~ xPosField : JTextField
        ~ y : int
        ~ yPosField : JTextField
        + actionPerformed()
        + arrangeCars()
        + closestRoadIndex()
        + isCoverRoad()
        {static} + main()
        + mouseClicked()
        + mouseEntered()
        + mouseExited()
        + mousePressed()
        + mouseReleased()
        + run()
        - Simulator()
    }
  }
  

  communityuni.com.Simulator .up.|> java.awt.event.ActionListener
  communityuni.com.Simulator .up.|> java.awt.event.MouseListener
  communityuni.com.Simulator .up.|> java.lang.Runnable
  communityuni.com.Simulator o-- communityuni.com.model.Road : road0


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
